#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd

while IFS=: read -r username _userid _ _ homedir _; do
	echo "Username: $username"
	echo "User ID: $_userid"
	echo "Home Directory: $homedir"
done < /etc/passwd