#!/usr/bin/env bash
#function to loop using while but 9th time says hi

i=1

while [ $i -le 10 ]; do
    if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
        i=$((i+1))
done